### ISSUE TITLE
Engenheiro(a) de Software

### ISSUE THREAD

**Issue by robertafonseca** [clj-br/vagas#12]
A MuvRH está em busca de um profissional para atuar na área da tecnologia, de forma híbrida, em uma empresa privada, de entretenimento e educação, jovem e que se encontra em um movimento bem bacana de expansão. Seus conteúdos vão desde política, história, cursos até arte e filosofia.

**Local da empresa:** Coração de São Paulo, na Avenida Paulista, no bairro Bela Vista.

**O que você vai fazer:**

- Explorar diversas frentes de trabalho e estar disposto a aprender com o time;
- Ser um influenciador nos rumos da empresa, expondo suas ideias;
- Experimentar as melhores soluções com pouca dependência e bastante autonomia;
- Poderá trabalhar com parte das tecnologias abaixo, voltado mais para as aplicações de front-end, back-end ou fullstack;
- Realizar programação funcional com Clojure, Clojurescript;
- Desenvolver APIs em GraphQL;
- Realizar desenvolvimento mobile Android e IOS com Kotlin e Swift;
- Atuar com tecnologia descentralizadas como: WebTorrent, Blockchain e IPFS;
- Utilizar React e Re-frame como tecnologias no front-end.

**O que você precisa ter:**

- Experiência mínima de 01 ano em desenvolvimento de software (back-end ou front-end);
- Conhecimento ou desejo em aprender Clojure e ClojureScript;
- Noções de programação funcional;
- Noções em tecnologias descentralizadas;
- Disponibilidade para atuar de forma presencial, pelo menos, uma semana durante o mês.

**Será um diferencial ter:**

- Trabalhado em startups;
- Atuado com desenvolvimento mobile em Android e IOS com Kotlin e Swift;
- Conhecimento em virtualização com Docker e Kubernetes e desenvolvimento de APIs em GraphQL;
- Experiência em desenvolvimento de microsserviços e comunicação assíncrona;
- Noções em Segurança da Informação.

**Diferenciais da empresa:**

- Autonomia para conduzir seus projetos com espaços seguros para trocas de ideias;
- Bônus quadrimestral conforme de desempenho individual e da empresa;
- Oportunidade real para adquirir participação acionária da empresa.

**Contrato:** PJ (Pessoa Jurídica).

**Remuneração e benefícios:** A remuneração será negociada de acordo com a nível de senioridade e conhecimentos técnicos + Plano de Saúde e Odonto da Porto Seguro com cobertura integral para o colaborador, podendo incluir dependentes mediante pagamento adicional + Seguro de Vida + Acesso total a todo o conteúdo disponibilizado na plataforma (cursos, podcasts, documentários e filmes) + Férias Remuneradas + Estacionamento.

**Como fazer contato:** Enviar o seu currículo para: cv@muvrh.com.br ou entrar em contato no WhatsApp: (51) 99731-2560. Importante escrever no assunto do e-mail o nome da vaga - Engenheiro(a) de Software.

**Comment by pbalduino** [comment]
Falta o nome da empresa.
